### ISSUE TITLE
CDAT Migration Phase 3: Refactor utility functions and legacy code

### ISSUE THREAD

**Issue by tomvothecoder** [E3SM-Project/e3sm_diags#734]
Once all sets have been refactored, we should refactor the the following functions and code:

TBD once #677 is merged. Look for all TODO statements and add to the list below.

### Todo:
 - [x] `general.regrid_to_lower_res()`
 - [x] `hybrid_to_plevs()` -- convert Z axis to mb units if in Pa
 - [x] Move all `plots/cartopy` files into root `/plot` file
- [x] Implement `e3sm_diags.driver.utils.regrid_subset_on_arm_coords()`, which is the refactored version of `e3sm_diags.utils.general.select_point`.

## Additional:
- #721 
- #726

**Comment by tomvothecoder** [comment]
This issue is no longer required because utility functions are refactored as we refactor the sets that use them.
