### ISSUE TITLE
[Refactor]: CDAT Migration Phase 3: testing, documentation update, prepare for new release

### ISSUE THREAD

**Issue by tomvothecoder** [E3SM-Project/e3sm_diags#843]
### Is your feature request related to a problem?

This is the final phase for the CDAT Migration work. It involves testing, cleaning up docs, and preparing the codebase for a new release.

## 1. Examples
In the root `examples/` directory, there are example run scripts that use the legacy way of configuring and running E3SM diagnostics. They should all be refactored to reflect the latest changes.

### Tasks

- [ ] Make sure `examples` scripts work and produce close/same results as `main` 
  - [ ] `ex1`
  - [ ] `ex2`
  - [ ] `ex3`
  - [ ] `ex4`
  - [ ] `ex5`
  - [ ] `ex6`
  - [ ] `ex7`
- [ ] Update `/tutorials` as needed 
- [ ] Update `/tutorials/2024` as needed
- [ ] Delete all `run_...py` scripts (only keep `run_v2_9_0_all_sets_E3SM_machines.py`

### Tasks

- [ ] Update documentation to reflect any changes in the refactored codebase

### Tasks

- [ ] Update changelog
- [ ] Remove unused modules that contain CDAT dependencies
  - [ ] `general.py`
  - [ ] `dataset.py`
- [ ] Remove CDAT dependencies from conda-env `.yml` files
- [ ] Remove any lingering CDAT references (e.g., docs, docstrings, etc.)
- [ ] Bump to v3.0.0

**Comment by tomvothecoder** [comment]
Closed by #846
